import { Worker } from 'node:worker_threads';
import path from 'node:path';

const PRIMARY_KEYS = { user_type: 'user_type_id', user: 'user_id', session: 'session_id', initiative: 'initiative_id', initiative_attribute: 'attribute_id', initiative_member: 'member_id', field: 'field_id', field_options: 'field_option_id', form: 'form_id', form_field: 'form_field_id', submission: 'submission_id', submission_value: 'submission_value_id', report_template: 'report_template_id', report_generation: 'report_generation_id', reports: 'id', surveys: 'id', qr_codes: 'qr_code_id', qr_scans: 'scan_id', feature: 'feature_id', feature_access: 'feature_access_id', permission: 'permission_id', role_permission: 'role_permission_id', survey_distribution: 'distribution_id', category: 'category_id', initiative_category: 'initiative_category_id', initiative_budget: 'budget_id', initiative_budget_history: 'history_id', initiative_goal: 'goal_id', goal_progress_history: 'history_id', trend: 'trend_id', audit_log: 'audit_id', goal_edit_conflict: 'conflict_id' };

function replacePlaceholders(sql) {
  let index = 0;
  let result = '';
  let quote = null;

  for (let position = 0; position < sql.length; position += 1) {
    const character = sql[position];
    const next = sql[position + 1];

    if (quote === 'line-comment') {
      result += character;
      if (character === '\n') quote = null;
      continue;
    }
    if (quote === 'block-comment') {
      result += character;
      if (character === '*' && next === '/') {
        result += next;
        position += 1;
        quote = null;
      }
      continue;
    }
    if (quote) {
      result += character;
      const closingCharacter = quote === '[' ? ']' : quote;
      if (character === closingCharacter) {
        if (next === closingCharacter) {
          result += next;
          position += 1;
        } else {
          quote = null;
        }
      }
      continue;
    }

    if (character === '-' && next === '-') {
      result += character + next;
      position += 1;
      quote = 'line-comment';
    } else if (character === '/' && next === '*') {
      result += character + next;
      position += 1;
      quote = 'block-comment';
    } else if (character === "'" || character === '"' || character === '[') {
      result += character;
      quote = character;
    } else if (character === '?') {
      result += `$${++index}`;
    } else {
      result += character;
    }
  }

  return result;
}

export function toPostgres(sql) {
  let text = replacePlaceholders(sql).replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP').replace(/AUTOINCREMENT/gi, 'GENERATED BY DEFAULT AS IDENTITY').replace(/INTEGER\s+PRIMARY\s+KEY\s+GENERATED BY DEFAULT AS IDENTITY/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/\[([^\]]+)\]/g, '"$1"').replace(/(?<!")\buser\b(?!")/gi, '"user"');
  if (/^\s*INSERT\s+OR\s+IGNORE/i.test(text)) {
    text = text.replace(/INSERT\s+OR\s+IGNORE/i, 'INSERT');
    text = /\bRETURNING\b/i.test(text)
      ? text.replace(/\s+RETURNING\b/i, ' ON CONFLICT DO NOTHING RETURNING')
      : text.replace(/;?\s*$/, ' ON CONFLICT DO NOTHING');
  }
  return text;
}

export class PostgresSyncDatabase {
  constructor(connectionString = process.env.DATABASE_URL) {
    if (!connectionString) throw new Error('DATABASE_URL must be set to use PostgreSQL.');
    this.buffer = new SharedArrayBuffer(8 * 1024 * 1024 + 8);
    this.signal = new Int32Array(this.buffer, 0, 2);
    this.bytes = new Uint8Array(this.buffer, 8);
    this.worker = new Worker(path.join(process.cwd(), 'scripts', 'postgres-sync-worker.cjs'), { workerData: { connectionString, responseBuffer: this.buffer } });
    this.worker.unref();
  }
  query(sql, values = []) {
    Atomics.store(this.signal, 0, 0); Atomics.store(this.signal, 1, 0);
    this.worker.postMessage({ text: toPostgres(sql), values });
    Atomics.wait(this.signal, 0, 0);
    const payload = JSON.parse(Buffer.from(this.bytes.subarray(0, Atomics.load(this.signal, 1))).toString());
    if (!payload.ok) { const error = new Error(payload.error.message); error.code = payload.error.code; throw error; }
    return payload;
  }
  prepare(sql) {
    const table = sql.match(/^\s*INSERT(?:\s+OR\s+IGNORE)?\s+INTO\s+"?([\w]+)"?/i)?.[1]?.toLowerCase();
    const primaryKey = PRIMARY_KEYS[table];
    return {
      get: (...values) => this.query(sql, values).rows[0],
      all: (...values) => this.query(sql, values).rows,
      run: (...values) => {
        const statement = primaryKey && /^\s*INSERT\b/i.test(sql) && !/\bRETURNING\b/i.test(sql) ? `${sql.replace(/;\s*$/, '')} RETURNING ${primaryKey}` : sql;
        const result = this.query(statement, values);
        return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.[primaryKey] };
      },
    };
  }
  exec(sql) { this.query(sql); }
  pragma() {}
  transaction(fn) { return (...args) => { this.query('BEGIN'); try { const result = fn(...args); this.query('COMMIT'); return result; } catch (error) { try { this.query('ROLLBACK'); } catch {} throw error; } }; }
}
