BEGIN;

CREATE TABLE user_type (
  user_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL UNIQUE,
  access_rank INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE "user" (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  phone_number TEXT,
  user_type_id INTEGER REFERENCES user_type(user_type_id),
  verified INTEGER NOT NULL DEFAULT 0,
  verification_token TEXT,
  token_expires_at TEXT
);

CREATE TABLE session (
  session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  csrf_token TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TEXT NOT NULL,
  absolute_expires_at TEXT NOT NULL,
  revoked_at TEXT
);

CREATE TABLE initiative (
  initiative_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_name TEXT NOT NULL UNIQUE,
  description TEXT,
  attributes TEXT DEFAULT '[]',
  questions TEXT DEFAULT '[]',
  settings TEXT DEFAULT '{}',
  summary_json TEXT,
  chart_data_json TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE initiative_attribute (
  attribute_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  data_type TEXT NOT NULL DEFAULT 'text' CHECK (data_type IN ('text','number','date','boolean','json')),
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  UNIQUE (initiative_id, name)
);

CREATE TABLE initiative_member (
  member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'participant',
  joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (initiative_id, user_id)
);

CREATE TABLE field (
  field_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_key TEXT NOT NULL UNIQUE,
  field_label TEXT NOT NULL,
  field_type TEXT NOT NULL CHECK (field_type IN ('text','number','date','boolean','select','multiselect','rating','json','choice','yesno')),
  scope TEXT NOT NULL DEFAULT 'common' CHECK (scope IN ('common','initiative_specific','staff_only')),
  initiative_id INTEGER REFERENCES initiative(initiative_id),
  attribute_id INTEGER REFERENCES initiative_attribute(attribute_id) ON DELETE SET NULL,
  is_filterable INTEGER NOT NULL DEFAULT 0,
  is_required_default INTEGER NOT NULL DEFAULT 0,
  is_reusable INTEGER NOT NULL DEFAULT 1,
  validation_rules TEXT
);

CREATE TABLE field_options (
  field_option_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id INTEGER NOT NULL REFERENCES field(field_id) ON DELETE CASCADE,
  option_value TEXT NOT NULL,
  display_label TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE form (
  form_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id),
  form_name TEXT NOT NULL,
  description TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_by_user_id INTEGER REFERENCES "user"(user_id),
  is_published INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE form_field (
  form_field_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id INTEGER NOT NULL REFERENCES form(form_id) ON DELETE CASCADE,
  field_id INTEGER NOT NULL REFERENCES field(field_id),
  display_order INTEGER NOT NULL DEFAULT 0,
  required INTEGER NOT NULL DEFAULT 0,
  is_hidden INTEGER NOT NULL DEFAULT 0,
  help_text TEXT,
  validation_rules TEXT,
  UNIQUE (form_id, field_id)
);

CREATE TABLE submission (
  submission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id),
  form_id INTEGER NOT NULL REFERENCES form(form_id),
  submitted_at TEXT DEFAULT CURRENT_TIMESTAMP,
  submitted_by_user_id INTEGER REFERENCES "user"(user_id)
);

CREATE TABLE submission_value (
  submission_value_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id INTEGER NOT NULL REFERENCES submission(submission_id) ON DELETE CASCADE,
  field_id INTEGER NOT NULL REFERENCES field(field_id),
  value_text TEXT,
  value_number REAL,
  value_date TEXT,
  value_bool INTEGER,
  value_json TEXT,
  UNIQUE (submission_id, field_id)
);

CREATE TABLE report_template (
  report_template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id),
  template_name TEXT NOT NULL,
  description TEXT,
  is_default INTEGER NOT NULL DEFAULT 0,
  is_public INTEGER NOT NULL DEFAULT 0,
  created_by_user_id INTEGER REFERENCES "user"(user_id),
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  config_json TEXT NOT NULL DEFAULT '{}',
  form_id INTEGER REFERENCES form(form_id)
);

CREATE TABLE report_generation (
  report_generation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_template_id INTEGER NOT NULL REFERENCES report_template(report_template_id),
  run_by_user_id INTEGER REFERENCES "user"(user_id),
  run_at TEXT DEFAULT CURRENT_TIMESTAMP,
  output_ref TEXT
);

CREATE TABLE feature (
  feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT
);

CREATE TABLE feature_access (
  feature_access_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_id INTEGER NOT NULL UNIQUE REFERENCES feature(feature_id),
  min_access_rank INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE permission (
  permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT
);

CREATE TABLE role_permission (
  role_permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_type_id INTEGER NOT NULL REFERENCES user_type(user_type_id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permission(permission_id) ON DELETE CASCADE,
  UNIQUE (user_type_id, permission_id)
);

CREATE TABLE surveys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  responses TEXT NOT NULL,
  submitted_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id INTEGER REFERENCES surveys(id) ON DELETE CASCADE,
  initiative_id INTEGER REFERENCES initiative(initiative_id),
  name TEXT NOT NULL DEFAULT '',
  description TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('generating','completed','failed','published','draft','archived')),
  created_by TEXT DEFAULT '',
  report_data TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE report_generation_log (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER REFERENCES initiative(initiative_id),
  report_id INTEGER REFERENCES reports(id),
  status TEXT NOT NULL CHECK (status IN ('started','completed','failed')),
  duration_ms INTEGER NOT NULL DEFAULT 0,
  input_rows INTEGER NOT NULL DEFAULT 0,
  output_rows INTEGER NOT NULL DEFAULT 0,
  filters_count INTEGER NOT NULL DEFAULT 0,
  expressions_count INTEGER NOT NULL DEFAULT 0,
  sorts_count INTEGER NOT NULL DEFAULT 0,
  trend_variables_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  ai_status TEXT,
  ai_duration_ms INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qr_codes (
  qr_code_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qr_code_key TEXT NOT NULL UNIQUE,
  qr_type TEXT NOT NULL CHECK (qr_type IN ('survey','report','survey_template')),
  target_id INTEGER,
  target_url TEXT NOT NULL,
  created_by_user_id INTEGER REFERENCES "user"(user_id),
  expires_at TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  description TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qr_scans (
  scan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qr_code_id INTEGER NOT NULL REFERENCES qr_codes(qr_code_id) ON DELETE CASCADE,
  ip_address TEXT,
  user_agent TEXT,
  referrer TEXT,
  converted_to_submission INTEGER,
  scanned_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE survey_distribution (
  distribution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_template_id TEXT NOT NULL,
  title TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','closed')),
  recipient_emails TEXT NOT NULL DEFAULT '[]',
  response_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id INTEGER REFERENCES "user"(user_id)
);

CREATE TABLE initiative_goal (
  goal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  goal_name TEXT NOT NULL,
  description TEXT,
  target_metric TEXT NOT NULL,
  target_value REAL NOT NULL,
  current_value REAL NOT NULL DEFAULT 0,
  weight REAL NOT NULL DEFAULT 1.0,
  scoring_method TEXT NOT NULL DEFAULT 'linear' CHECK (scoring_method IN ('linear','threshold','binary')),
  deadline TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  created_by_user_id INTEGER REFERENCES "user"(user_id)
);

CREATE TABLE category (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE initiative_category (
  initiative_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES category(category_id) ON DELETE CASCADE,
  added_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (initiative_id, category_id)
);

CREATE TABLE initiative_budget (
  budget_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  fiscal_year INTEGER NOT NULL,
  department TEXT NOT NULL DEFAULT 'General',
  personnel REAL NOT NULL DEFAULT 0 CHECK (personnel >= 0),
  equipment REAL NOT NULL DEFAULT 0 CHECK (equipment >= 0),
  operations REAL NOT NULL DEFAULT 0 CHECK (operations >= 0),
  travel REAL NOT NULL DEFAULT 0 CHECK (travel >= 0),
  personnel_spent REAL NOT NULL DEFAULT 0,
  equipment_spent REAL NOT NULL DEFAULT 0,
  operations_spent REAL NOT NULL DEFAULT 0,
  travel_spent REAL NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (initiative_id, fiscal_year)
);

CREATE TABLE initiative_budget_history (
  history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id INTEGER NOT NULL REFERENCES initiative_budget(budget_id) ON DELETE CASCADE,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  fiscal_year INTEGER NOT NULL,
  department TEXT NOT NULL,
  personnel REAL NOT NULL DEFAULT 0 CHECK (personnel >= 0),
  equipment REAL NOT NULL DEFAULT 0 CHECK (equipment >= 0),
  operations REAL NOT NULL DEFAULT 0 CHECK (operations >= 0),
  travel REAL NOT NULL DEFAULT 0 CHECK (travel >= 0),
  changed_by_user_id INTEGER REFERENCES "user"(user_id),
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE goal_progress_history (
  history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id INTEGER NOT NULL REFERENCES initiative_goal(goal_id) ON DELETE CASCADE,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  recorded_value REAL NOT NULL,
  target_value REAL NOT NULL,
  score REAL NOT NULL,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE goal_edit_conflict (
  conflict_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id INTEGER NOT NULL REFERENCES initiative_goal(goal_id) ON DELETE CASCADE,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved')),
  resolution TEXT CHECK (resolution IS NULL OR resolution IN ('applied_proposal','rejected_proposal')),
  expected_updated_at TEXT NOT NULL,
  detected_server_updated_at TEXT NOT NULL,
  proposed_patch TEXT NOT NULL,
  server_snapshot TEXT NOT NULL,
  submitter_email TEXT NOT NULL,
  resolved_by_email TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  resolved_at TEXT
);

CREATE TABLE trend (
  trend_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  trend_key TEXT NOT NULL UNIQUE,
  report_id TEXT,
  attributes TEXT NOT NULL DEFAULT '[]',
  direction TEXT NOT NULL CHECK (direction IN ('up','down','stable')),
  magnitude REAL NOT NULL DEFAULT 0,
  time_period TEXT,
  enabled_display INTEGER NOT NULL DEFAULT 1,
  enabled_calc INTEGER NOT NULL DEFAULT 1,
  description TEXT
);

CREATE TABLE audit_log (
  audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event TEXT NOT NULL,
  user_email TEXT,
  target_type TEXT,
  target_id TEXT,
  reason_type TEXT,
  reason_text TEXT,
  payload TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_session_user_id ON session(user_id);
CREATE INDEX idx_session_expires_at ON session(expires_at);
CREATE INDEX idx_role_permission_user_type ON role_permission(user_type_id);
CREATE INDEX idx_role_permission_permission ON role_permission(permission_id);
CREATE INDEX idx_submission_initiative_date ON submission(initiative_id, submitted_at DESC);
CREATE INDEX idx_initiative_attribute_initiative ON initiative_attribute(initiative_id);
CREATE INDEX idx_field_attribute ON field(attribute_id);
CREATE INDEX idx_submission_form_date ON submission(form_id, submitted_at DESC);
CREATE INDEX idx_submission_value_submission ON submission_value(submission_id);
CREATE INDEX idx_submission_value_field ON submission_value(field_id);
CREATE INDEX idx_qr_codes_key ON qr_codes(qr_code_key);
CREATE INDEX idx_qr_scans_code_id ON qr_scans(qr_code_id);
CREATE INDEX idx_qr_scans_scanned_at ON qr_scans(scanned_at DESC);
CREATE INDEX idx_surveys_submitted_at ON surveys(submitted_at DESC);
CREATE INDEX idx_reports_survey_id ON reports(survey_id);
CREATE INDEX idx_reports_initiative_id ON reports(initiative_id);
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);
CREATE INDEX idx_report_generation_log_created_at ON report_generation_log(created_at DESC);
CREATE INDEX idx_report_generation_log_status ON report_generation_log(status);
CREATE INDEX idx_distribution_status ON survey_distribution(status);
CREATE INDEX idx_distribution_dates ON survey_distribution(start_date, end_date);
CREATE INDEX idx_goal_initiative ON initiative_goal(initiative_id);
CREATE INDEX idx_goal_history_initiative ON goal_progress_history(initiative_id, recorded_at);
CREATE INDEX idx_goal_history_goal ON goal_progress_history(goal_id, recorded_at);
CREATE INDEX idx_goal_edit_conflict_pending ON goal_edit_conflict(status, created_at DESC);
CREATE INDEX idx_goal_edit_conflict_goal ON goal_edit_conflict(goal_id);
CREATE INDEX idx_category_name ON category(category_name);
CREATE INDEX idx_initiative_category_initiative ON initiative_category(initiative_id);
CREATE INDEX idx_initiative_category_category ON initiative_category(category_id);
CREATE INDEX idx_initiative_budget_history_budget ON initiative_budget_history(budget_id);
CREATE INDEX idx_initiative_budget_history_initiative ON initiative_budget_history(initiative_id);
CREATE INDEX idx_trend_initiative ON trend(initiative_id);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at DESC);

COMMIT;
