BEGIN;

CREATE TABLE IF NOT EXISTS initiative_attribute (
  attribute_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  data_type TEXT NOT NULL DEFAULT 'text' CHECK (data_type IN ('text','number','date','boolean','json')),
  initiative_id INTEGER NOT NULL REFERENCES initiative(initiative_id) ON DELETE CASCADE,
  UNIQUE (initiative_id, name)
);

ALTER TABLE field
  ADD COLUMN IF NOT EXISTS attribute_id INTEGER REFERENCES initiative_attribute(attribute_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_initiative_attribute_initiative ON initiative_attribute(initiative_id);
CREATE INDEX IF NOT EXISTS idx_field_attribute ON field(attribute_id);

INSERT INTO initiative_attribute (name, data_type, initiative_id)
SELECT attribute_name, 'text', i.initiative_id
FROM initiative i
CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(NULLIF(i.attributes, ''), '[]')::jsonb) AS attribute_name
ON CONFLICT (initiative_id, name) DO NOTHING;

COMMIT;
